# Welcome to Jekyll Paper for Github
#
# This is the configuration file for your blog, please change these items after forked.

title: Just the F*cking Recipe
email: farts@just-the.recipes
name: aloria
description: >- # this means to ignore newlines until "baseurl:"
  I don't need your life story. I just want some food.
keywords: [cooking, recipes]
baseurl: '' # the subpath of your site, e.g. /`blog
url: 'https://just-the.recipes' # the base hostname & protocol for your site, e.g. http://example.com
domain: 'just-the.recipes' # the domain name for your site, e.g. example.com
language: en
# Supported languages list:
# en: English
# de: Deutsche (German)
# es: Español (Spanish)
# fr: Français (French)
# ja: 日本語 (Japanese)
# pt: Português (Portuguese)
# zh-cn: 简体中文 (Simplified Chinese)
# zh-tw: 繁體中文 (Traditional Chinese)
timezone: America/New_York

future: false

analytics: G-42HG3L86FD

comments: false # enable comments
disqus: # disqus account

mathjax: false # Math support
diagram: false # Diagrams support

paginate: 20
paginate_path: '/page:num/'

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

# Build settings
markdown: kramdown
plugins:
  - github-pages
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
